package purchasefeature;

import basesteps.BaseSteps;
import org.testng.Assert;
import org.testng.annotations.Test;
import pages.*;

public class TestPurchaseFeature extends BaseSteps {
    @Test
    public void testsignup() throws InterruptedException {
        SignUpPage signUpPage = homepage.clickonsignup();
        signUpPage.entersignupusername();
        signUpPage.entersignuppassword();
        signUpPage.clickonsignupbutton();
        String actualResult = signUpPage.getsignupalerttext();
        String expectedResult = "Sign up successful.";
        Assert.assertTrue(actualResult.contains(expectedResult));
        signUpPage.acceptalert();
        Thread.sleep(1000);
        LogInPage logInPage = homepage.clickonlogin();
        Thread.sleep(1000);
        logInPage.enterloginusername("MostafaGhobashy");
        logInPage.enterloginpassword("Ghobash11");
        logInPage.clickonloginbutton();
        Thread.sleep(2000);
        String actualresult2 = logInPage.getloginusertext();
        String expectedresult2 = "Welcome MostafaGhobashy";
        Assert.assertTrue(actualresult2.contains(expectedresult2));
        Thread.sleep(1000);
        LapTopPage lapTopPage = homepage.clickonlaptops();
        Thread.sleep(1000);
        Product1Page product1Page = lapTopPage.clickonproduct1();
        Thread.sleep(1000);
        product1Page.addproduct1tocart();
        Thread.sleep(1000);
        String actualresult3 = product1Page.getprodduct1alerttext();
        String expectedresult3 = "Product added";
        Assert.assertTrue(actualresult3.contains(expectedresult3));
        Thread.sleep(1000);
        product1Page.acceptproduct1alert();
        Thread.sleep(1000);
        CartPage cartPage = product1Page.clickoncart();
        Thread.sleep(2000);
        String actualresultproduct1name = cartPage.getproduct1name();
        String expectedresultproduct1name = "Sony vaio i5";
        Assert.assertTrue(actualresultproduct1name.contains(expectedresultproduct1name));
        Thread.sleep(1000);
        String actualresultproduct1price = cartPage.getproduct1price();
        String expectedresultproduct1price = "790";
        Assert.assertTrue(actualresultproduct1price.contains(expectedresultproduct1price));
        Thread.sleep(1000);
        cartPage.clickonhome();
        Thread.sleep(1000);
        homepage.clickonlaptops();
        Thread.sleep(1000);
        Product2Page product2Page = lapTopPage.clickonproduct2();
        Thread.sleep(1000);
        product2Page.addproduct2tocart();
        Thread.sleep(1000);
        String actualresult4 = product2Page.getprodduct2alerttext();
        String expectedresult4 = "Product added";
        Assert.assertTrue(actualresult4.contains(expectedresult4));
        Thread.sleep(1000);
        product2Page.acceptproduct2alert();
        Thread.sleep(1000);
        product2Page.clickoncart2();
        Thread.sleep(2000);
        String actualresultproduct2name = cartPage.getproduct2name();
        String expectedresultproduct2name = "Sony vaio i7";
        Assert.assertTrue(actualresultproduct2name.contains(expectedresultproduct2name));
        Thread.sleep(1000);
        String actualresultproduct2price = cartPage.getproduct2price();
        String expectedresultproduct2price = "790";
        Assert.assertTrue(actualresultproduct2price.contains(expectedresultproduct2price));
        String actualresulttotalprice = cartPage.gettotalprice();
        String expectedresulttotalprice = "1580";
        Assert.assertTrue(actualresulttotalprice.contains(expectedresulttotalprice));
        Thread.sleep(1000);
        PlaceOrderPage placeOrderPage = cartPage.clickonplaceorder();
        Thread.sleep(1000);
        placeOrderPage.entername("Mostafa Ghobashy");
        placeOrderPage.entercountry("Egypt");
        placeOrderPage.entercity("Cairo");
        placeOrderPage.entercreditcard("41115986322520");
        placeOrderPage.entermonth("12");
        placeOrderPage.enteryear("2024");
        placeOrderPage.clickonpurchasebutton();
        Thread.sleep(1000);
        String actualresultpurchase = placeOrderPage.successpurchase();
        String expectedresultpurchase = "Thank you for your purchase!";
        Assert.assertTrue(actualresultpurchase.contains(expectedresultpurchase));
    }
}
